spring:
  application:
    name: sistemabancario
  datasource:
    url: jdbc:h2:mem:banco
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      pah: /h2-console